export const GET_OFFICERS = 'GET_OFFICERS';
export const GET_CRIMINALS = 'GET_CRIMINALS';
export const GET_SINGLE_CRIMINAL = 'GET_SINGLE_CRIMINAL';
export const ADD_OFFICER = 'ADD_OFFICER';
export const ADD_CRIMINAL = 'ADD_CRIMINAL';
export const EDIT_CRIMINAL = 'EDIT_CRIMINAL';